// Home Type
export const IS_LOADING = 'IS_LOADING';
export const API_REQUEST = 'API_REQUEST';
export const API_SUCCESS = 'API_SUCCESS';
export const API_FAILURE = 'API_FAILURE';
export const API_LIST_END = 'API_LIST_END';
export const RESET_MOVIE = 'RESET_MOVIE';

// Detail Movie Type
export const API_DETAIL_MOVIE_REQUEST = 'API_DETAIL_MOVIE_REQUEST';
export const API_DETAIL_MOVIE_SUCCESS = 'API_DETAIL_MOVIE_SUCCESS';
export const API_DETAIL_MOVIE_FAILURE = 'API_DETAIL_MOVIE_FAILURE';
export const API_RELATED_MOVIE_SUCCESS = 'API_RELATED_MOVIE_SUCCESS';
export const API_CAST_MOVIE_SUCCESS = 'API_CAST_MOVIE_SUCCESS';
export const RESET_DETAIL_MOVIE_MOVIE = 'RESET_DETAIL_MOVIE_MOVIE';

// Detail Person Type
export const API_DETAIL_PERSON_REQUEST = 'API_DETAIL_PERSON_REQUEST';
export const API_DETAIL_PERSON_SUCCESS = 'API_DETAIL_PERSON_SUCCESS';
export const API_MOVIES_PERSON_SUCCESS = 'API_MOVIES_PERSON_SUCCESS';
export const API_DETAIL_PERSON_FAILURE = 'API_DETAIL_PERSON_FAILURE';
export const RESET_DETAIL_PERSON = 'RESET_DETAIL_PERSON';
